name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: apps/chatApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack and Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          # Add Corepack's bin directory to PATH
          echo "$(corepack yarn global bin)" >> $GITHUB_PATH
          # Debug information
          echo "PATH: $PATH"
          which yarn
          yarn --version
          corepack yarn --version

      - name: Install Dependencies
        run: corepack yarn install

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS App
        run: corepack yarn e2e:build:ios

      - name: Run E2E Tests
        run: corepack yarn e2e:test:ios

  test-android:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: apps/chatApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Enable Corepack and Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          # Add Corepack's bin directory to PATH
          echo "$(corepack yarn global bin)" >> $GITHUB_PATH
          # Debug information
          echo "PATH: $PATH"
          which yarn
          yarn --version
          corepack yarn --version

      - name: Install Dependencies
        run: corepack yarn install

      - name: Build Android App
        run: corepack yarn e2e:build:android

      - name: Run E2E Tests
        run: corepack yarn e2e:test:android
