name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: apps/chatApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Yarn with Corepack
        run: |
          # Remove any existing yarn installation
          rm -rf /Users/runner/.yarn
          # Enable corepack
          corepack enable
          # Install and activate yarn 4.9.1
          corepack prepare yarn@4.9.1 --activate
          # Force yarn to use the corepack version
          export PATH="$(corepack yarn global bin):$PATH"
          # Debug output
          echo "Using yarn from: $(which yarn)"
          echo "Yarn version: $(yarn --version)"

      - name: Install Dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          PATH: '$(corepack yarn global bin):$PATH'
        run: yarn install

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS App
        env:
          PATH: '$(corepack yarn global bin):$PATH'
        run: yarn e2e:build:ios

      - name: Run E2E Tests
        env:
          PATH: '$(corepack yarn global bin):$PATH'
        run: yarn e2e:test:ios

  test-android:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: apps/chatApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Yarn with Corepack
        run: |
          # Remove any existing yarn installation
          rm -rf /Users/runner/.yarn
          # Enable corepack
          corepack enable
          # Install and activate yarn 4.9.1
          corepack prepare yarn@4.9.1 --activate
          # Force yarn to use the corepack version
          export PATH="$(corepack yarn global bin):$PATH"
          # Debug output
          echo "Using yarn from: $(which yarn)"
          echo "Yarn version: $(yarn --version)"

      - name: Install Dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          PATH: '$(corepack yarn global bin):$PATH'
        run: yarn install

      - name: Build Android App
        env:
          PATH: '$(corepack yarn global bin):$PATH'
        run: yarn e2e:build:android

      - name: Run E2E Tests
        env:
          PATH: '$(corepack yarn global bin):$PATH'
        run: yarn e2e:test:android
