name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: apps/chatApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Yarn with Corepack
        run: |
          # Remove any existing yarn installation
          rm -rf /Users/runner/.yarn
          # Enable corepack
          corepack enable
          # Install and activate yarn 4.9.1
          corepack prepare yarn@4.9.1 --activate
          # Debug output
          echo "Using yarn from: $(which yarn)"
          echo "Yarn version: $(yarn --version)"

      - name: Install Dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: yarn install

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS App
        run: |
          # Ensure xcodebuild is available
          sudo xcode-select -s /Applications/Xcode.app
          # Build the app
          yarn e2e:build:ios

      - name: Run E2E Tests
        run: yarn e2e:test:ios

  test-android:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: apps/chatApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Yarn with Corepack
        run: |
          # Remove any existing yarn installation
          rm -rf /Users/runner/.yarn
          # Enable corepack
          corepack enable
          # Install and activate yarn 4.9.1
          corepack prepare yarn@4.9.1 --activate
          # Debug output
          echo "Using yarn from: $(which yarn)"
          echo "Yarn version: $(yarn --version)"

      - name: Install Dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: yarn install

      - name: Setup Android Build Tools
        run: |
          # Ensure Android SDK tools are in PATH
          echo "$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          # Make gradlew executable
          chmod +x android/gradlew

      - name: Build Android App
        run: yarn e2e:build:android

      - name: Run E2E Tests
        run: yarn e2e:test:android
